name: Introduction to Data Science
description: Using Python in the newsroom
meta_description: "Introduction to Data Science with Python"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://tswicegood.github.io/python-data-science-intro'

url: 'http://tswicegood.github.io/python-data-science-intro'
author: "Tom Meagher and Travis Swicegood"
